import 'package:flutter/material.dart';

class Product {
  final String? image, title, description;
  final int? price, size, id;
  final Color? color;
  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.description,
    this.size,
    this.color,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Air Jordan",
      price: 678,
      size: 42,
      description: dummyText,
      image: "assets/images/tenis_1.png",
      color: const Color(0xFF73c3f9),
      ),
       
  Product(
      id: 2,
      title: "Air Jordan",
      price: 735,
      size: 40,
      description: dummyText,
      image: "assets/images/tenis_2.png",
      color: const Color(0xFFfe4650)),
  Product(
      id: 3,
      title: "Air Jordan",
      price: 814,
      size: 41,
      description: dummyText,
      image: "assets/images/tenis_3.png",
      color: const Color(0xFFf1b90d)),
  Product(
      id: 4,
      title: "Air Jordan",
      price: 469,
      size: 43,
      description: dummyText,
      image: "assets/images/tenis_4.png",
      color: const Color(0xFF928f96)),
  Product(
      id: 5,
      title: "Air Jordan",
      price: 994,
      size: 42,
      description: dummyText,
      image: "assets/images/tenis_5.png",
      color: const Color(0xFFcb395b)),
  Product(
    id: 6,
    title: "Air Jordan",
    price: 1284,
    size: 45,
    description: dummyText,
    image: "assets/images/tenis_6.png",
    color: const Color(0xFFa1a3a8),
  ),
  Product(
    id: 7,
    title: "Air Max",
    price: 1100,
    size: 42,
    description: dummyText,
    image: "assets/images/airmax.png",
    color: const Color(0xFF2b6fad),
  ),
  Product(
      id: 8,
      title: "Air Max",
      price: 338,
      size: 40,
      description: dummyText,
      image: "assets/images/airmax2.png",
      color: const Color(0xFFb5b5b5)),
  Product(
      id: 9,
      title: "Air Max",
      price: 124,
      size: 41,
      description: dummyText,
      image: "assets/images/airmax3.png",
      color: const Color(0xFFa80c1c)),
  Product(
      id: 10,
      title: "Air Max",
      price: 579,
      size: 43,
      description: dummyText,
      image: "assets/images/airmax4.png",
      color: const Color(0xFF27272b)),
  Product(
      id: 11,
      title: "Air Max",
      price: 894,
      size: 42,
      description: dummyText,
      image: "assets/images/airmax5.png",
      color: const Color(0xFFc09867)),
  Product(
    id: 12,
    title: "Air Max",
    price: 1473,
    size: 45,
    description: dummyText,
    image: "assets/images/airmax6.png",
    color: const Color(0xFFc3af9b),
  ),
  Product(
    id: 13,
    title: "Air Force",
    price: 284,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce.png",
    color: const Color(0xFF27272b),
  ),
  Product(
    id: 14,
    title: "Air Force",
    price: 462,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce1.png",
    color: const Color(0xFF928f96),
  ),
  Product(
    id: 15,
    title: "Air Force",
    price: 690,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce2.png",
    color: const Color(0xFFbd212e),
  ),
  Product(
    id: 16,
    title: "Air Force",
    price: 821,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce3.png",
    color: const Color(0xFFe27e4f),
  ),
  Product(
    id: 17,
    title: "Air Force",
    price: 1012,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce4.png",
    color: const Color(0xFF7fae64),
  ),
  Product(
    id: 18,
    title: "Air Force",
    price: 250,
    size: 45,
    description: dummyText,
    image: "assets/images/airforce5.png",
    color: const Color(0xFF8a6737),
  ),
  Product(
    id: 19,
    title: "DownShifter",
    price: 1156,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter.png",
    color: const Color(0xFF79507e),
  ),
  Product(
    id: 20,
    title: "DownShifter",
    price: 400,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter1.png",
    color: const Color(0xFF3d444a),
  ),
  Product(
    id: 21,
    title: "DownShifter",
    price: 650,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter2.png",
    color: const Color(0xFF928f96),
  ),
  Product(
    id: 22,
    title: "DownShifter",
    price: 300,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter3.png",
    color: const Color(0xFF2c4299),
  ),
  Product(
    id: 23,
    title: "DownShifter",
    price: 900,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter4.png",
    color: const Color(0xFF363635),
  ),
  Product(
    id: 24,
    title: "DownShifter",
    price: 1250,
    size: 45,
    description: dummyText,
    image: "assets/images/downshifter5.png",
    color: const Color(0xFFbaa2d5),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
